import { useEffect, useMemo, useState } from 'react';

type Fact = { label: string; value: string; version: number };
type Asset = { id: string; type: string; channel: string; owner: string; deadline: string; body: string; factKeys: string[]; status: string; version: number; approval: { version: number; actor: string; at: string } | null; reviewNote?: string };
type Snapshot = { workspace: { name: string; role: string; synthetic: boolean }; campaign: { id: string; name: string; client: string; updatedAt: string; facts: Record<string, Fact>; assets: Asset[]; changes: { type?: string; factKey?: string; value?: string; previous?: string; actor: string; at: string }[] } };
type View = 'overview' | 'calendar' | 'review' | 'map' | 'reports' | 'portal';

const api = async (url: string, options?: RequestInit) => { const response = await fetch(url, { headers: { 'content-type': 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; };

function App() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [view, setView] = useState<View>(() => { const candidate = window.location.hash.slice(1) as View; return ['overview', 'calendar', 'review', 'map', 'reports', 'portal'].includes(candidate) ? candidate : 'overview'; });
  const [selectedAsset, setSelectedAsset] = useState<string | null>(null);
  const [notice, setNotice] = useState('');
  const [report, setReport] = useState<{ rows: number; checks: { line: number; severity: string; code: string; message: string }[]; valid: boolean } | null>(null);

  const refresh = async () => setSnapshot(await api('/api/snapshot'));
  useEffect(() => { refresh().catch((error) => setNotice(error.message)); }, []);
  const selected = snapshot?.campaign.assets.find((asset) => asset.id === selectedAsset) || snapshot?.campaign.assets[0];
  const outdated = snapshot?.campaign.assets.filter((asset) => asset.status === 'outdated').length ?? 0;
  const pending = snapshot?.campaign.assets.filter((asset) => asset.status !== 'approved').length ?? 0;
  const navigate = (next: View) => { window.history.replaceState(null, '', next === 'overview' ? window.location.pathname : `#${next}`); setView(next); };

  async function changeFact(key: string, value: string) { try { await api(`/api/facts/${key}`, { method: 'PATCH', body: JSON.stringify({ value, actor: 'owner' }) }); await refresh(); setNotice(`${snapshot?.campaign.facts[key]?.label || key} updated. Linked approvals were reset.`); } catch (error) { setNotice((error as Error).message); } }
  async function revise(body: string) { if (!selected) return; try { await api(`/api/assets/${selected.id}`, { method: 'PATCH', body: JSON.stringify({ body, actor: 'editor' }) }); await refresh(); setNotice('Revision saved. Client approval is required for this version.'); } catch (error) { setNotice((error as Error).message); } }
  async function approve() { if (!selected) return; try { await api(`/api/assets/${selected.id}/approve`, { method: 'POST', body: JSON.stringify({ actor: 'client' }) }); await refresh(); setNotice('Approved for this asset version.'); } catch (error) { setNotice((error as Error).message); } }

  if (!snapshot) return <main className="loading"><span className="pulse" /> Loading StudioDesk…</main>;
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">SD</span><span><strong>StudioDesk</strong><small>campaign workspace</small></span></div>
      <div className="workspace-pill"><span className="avatar">CM</span><span><b>{snapshot.workspace.name}</b><small>Owner workspace</small></span><span className="chevron">⌄</span></div>
      <nav aria-label="Workspace navigation">{([['overview','Overview','◈'],['calendar','Content calendar','▦'],['review','Visual review','◌'],['map','Change map','⌁'],['reports','Reports','▤'],['portal','Client portal','↗']] as [View,string,string][]).map(([key,label,icon]) => <button key={key} className={view === key ? 'nav-item active' : 'nav-item'} onClick={() => navigate(key)}><span>{icon}</span>{label}{key === 'review' && pending > 0 ? <em>{pending}</em> : null}</button>)}</nav>
      <div className="sidebar-foot"><span className="status-dot" /> Demo mode <span className="synthetic">synthetic data</span></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><p className="eyebrow">Fictional client workspace</p><h1>{snapshot.campaign.name}</h1></div><div className="top-actions"><span className="privacy"><span className="lock">⌁</span> No platform connections</span><button className="ghost" onClick={() => navigate('portal')}>Preview client view ↗</button><span className="user">SS</span></div></header>
      {notice && <div className="notice" role="status"><span>i</span>{notice}<button onClick={() => setNotice('')}>×</button></div>}
      {view === 'overview' && <Overview snapshot={snapshot} outdated={outdated} pending={pending} onFact={changeFact} onView={navigate} />}
      {view === 'calendar' && <Calendar assets={snapshot.campaign.assets} />}
      {view === 'review' && <Review assets={snapshot.campaign.assets} selected={selected} onSelect={setSelectedAsset} onRevise={revise} onApprove={approve} />}
      {view === 'map' && <ChangeMap snapshot={snapshot} onFact={changeFact} />}
      {view === 'reports' && <Reports report={report} setReport={setReport} />}
      {view === 'portal' && <Portal snapshot={snapshot} pending={pending} onApprove={approve} />}
      <footer className="disclaimer">Personal open-source demo · Synthetic campaign · Not client work · Local-first by design</footer>
    </main>
  </div>;
}

function Overview({ snapshot, outdated, pending, onFact, onView }: { snapshot: Snapshot; outdated: number; pending: number; onFact: (key: string, value: string) => void; onView: (view: View) => void }) {
  const { campaign } = snapshot;
  return <section className="page"><div className="hero-card"><div><span className="demo-label">● Personal demo · synthetic data</span><h2>Keep every campaign detail in sync.</h2><p>When an offer or venue changes, StudioDesk shows the captions, creatives and approvals that need attention.</p><div className="hero-actions"><button className="primary" onClick={() => onView('map')}>Open change map <span>→</span></button><button className="text-btn" onClick={() => onView('review')}>Review assets</button></div></div><div className="hero-graphic"><div className="ring ring-one" /><div className="ring ring-two" /><div className="signal-card"><span>campaign health</span><strong>{pending ? 'Needs review' : 'Ready to hand off'}</strong><small>{pending ? `${pending} assets need attention` : 'All versions approved'}</small></div></div></div>
    <div className="stats"><Stat value={campaign.assets.length.toString()} label="Tracked assets" note="across 4 channels" /><Stat value={outdated.toString().padStart(2,'0')} label="Needs update" note={outdated ? 'after latest change' : 'nothing flagged'} tone={outdated ? 'amber' : ''} /><Stat value={campaign.changes.length.toString().padStart(2,'0')} label="Change history" note="auditable actions" /><Stat value="100%" label="Human review" note="approval per version" /></div>
    <div className="section-heading"><div><p className="eyebrow">Campaign controls</p><h3>Change a fact, see the consequences</h3></div><span className="muted">Try the sample workflow</span></div>
    <div className="fact-grid">{Object.entries(campaign.facts).map(([key, fact]) => <div className="fact-card" key={key}><div className="fact-icon">{key === 'venue' ? '⌂' : key === 'price' ? '₹' : key === 'date' ? '◷' : key === 'bookingUrl' ? '↗' : '◇'}</div><div><span>{fact.label}</span><strong>{fact.value}</strong><small>Version {fact.version}</small></div>{key === 'venue' && <button className="small-action" onClick={() => onFact(key, 'Harbour Hall')}>Change</button>}{key === 'price' && <button className="small-action" onClick={() => onFact(key, '₹349')}>Change</button>}</div>)}</div>
    <div className="lower-grid"><section className="panel"><div className="panel-head"><div><p className="eyebrow">Recent activity</p><h3>What changed</h3></div><button className="link-btn" onClick={() => onView('map')}>View history →</button></div>{campaign.changes.length ? campaign.changes.slice(0,4).map((change, index) => <div className="activity" key={`${change.at}-${index}`}><span className="activity-icon">{change.type === 'approval' ? '✓' : change.type === 'revision' ? '✎' : '↻'}</span><div><strong>{change.type === 'approval' ? 'Asset approved' : change.type === 'revision' ? 'Asset revised' : `${campaign.facts[change.factKey || 'date']?.label || 'Fact'} changed`}</strong><span>{change.previous ? `${change.previous} → ${change.value}` : 'A new version needs review'}</span></div><time>{new Date(change.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div>) : <div className="empty"><span>✦</span><p>No changes yet. Try changing the venue above.</p></div>}</section><section className="panel next-panel"><div className="panel-head"><div><p className="eyebrow">Suggested next step</p><h3>Review your handoff</h3></div><span className="step-number">01</span></div><p>Open the change map to see dependencies, then approve each corrected version before sharing with the client.</p><button className="primary wide" onClick={() => onView('review')}>Open review queue <span>→</span></button></section></div>
  </section>;
}
function Stat({ value, label, note, tone = '' }: { value: string; label: string; note: string; tone?: string }) { return <div className="stat"><strong className={tone}>{value}</strong><span>{label}</span><small>{note}</small></div>; }
function Calendar({ assets }: { assets: Asset[] }) { return <section className="page"><PageTitle eyebrow="Content calendar" title="Everything in one place" sub="Deadlines, owners and approval state for this synthetic campaign." /><div className="toolbar"><button className="primary">+ Add content</button><button className="ghost">All channels⌄</button><button className="ghost">All owners⌄</button></div><div className="table-card"><table><thead><tr><th>Asset</th><th>Channel</th><th>Owner</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{assets.map((asset) => <tr key={asset.id}><td><span className="asset-type">{asset.type[0]}</span><b>{asset.type}</b></td><td>{asset.channel}</td><td>{asset.owner}</td><td>{asset.deadline}</td><td><Status status={asset.status} /></td></tr>)}</tbody></table></div></section>; }
function Review({ assets, selected, onSelect, onRevise, onApprove }: { assets: Asset[]; selected?: Asset; onSelect: (id: string) => void; onRevise: (body: string) => void; onApprove: () => void }) { const [draft, setDraft] = useState(selected?.body || ''); useEffect(() => setDraft(selected?.body || ''), [selected?.id, selected?.body]); return <section className="page"><PageTitle eyebrow="Visual review" title="Approve the exact version" sub="A revision always resets the previous approval. Use the sample assets to try the client workflow." /><div className="review-layout"><div className="asset-list">{assets.map((asset) => <button key={asset.id} onClick={() => onSelect(asset.id)} className={selected?.id === asset.id ? 'asset-row selected' : 'asset-row'}><span className="asset-thumb">{asset.type[0]}</span><span><b>{asset.type}</b><small>{asset.channel} · {asset.owner}</small></span><Status status={asset.status} /></button>)}</div><div className="editor panel">{selected && <><div className="editor-head"><div><span className="demo-label">{selected.channel} · version {selected.version}</span><h3>{selected.type}</h3></div><Status status={selected.status} /></div><div className="mock-canvas"><div className="poster-lines"><span /><i /><span /><small>{selected.type === 'Poster' ? 'Café Monsoon' : 'Personal demo preview'}</small></div><p>Visual preview placeholder — upload a real campaign asset in your private workspace.</p></div><label className="field-label">Copy or handoff notes<textarea value={draft} onChange={(event) => setDraft(event.target.value)} rows={5} /></label><div className="editor-actions"><button className="ghost" onClick={() => onRevise(draft)}>Save revision</button><button className="primary" onClick={onApprove}>Approve version {selected.version}</button></div><p className="helper">{selected.reviewNote || 'Approved versions remain valid until a linked fact or asset changes.'}</p></>}</div></div></section>; }
function ChangeMap({ snapshot, onFact }: { snapshot: Snapshot; onFact: (key: string, value: string) => void }) { const [focus, setFocus] = useState('venue'); const fact = snapshot.campaign.facts[focus]; const affected = snapshot.campaign.assets.filter((asset) => asset.factKeys.includes(focus)); return <section className="page"><PageTitle eyebrow="Dependency map" title="See what a change touches" sub="Select a campaign fact. Every connected asset is counted once, even when it depends on two changed facts." /><div className="map-layout"><div className="fact-rail"><span className="rail-title">Campaign facts</span>{Object.entries(snapshot.campaign.facts).map(([key, item]) => <button key={key} className={focus === key ? 'map-fact active' : 'map-fact'} onClick={() => setFocus(key)}><span className="fact-icon mini">{key === 'venue' ? '⌂' : key === 'price' ? '₹' : '◷'}</span><span><b>{item.label}</b><small>{item.value}</small></span></button>)}<button className="primary wide" onClick={() => onFact(focus, focus === 'venue' ? 'Harbour Hall' : focus === 'price' ? '₹349' : 'Updated value')}>Change {fact.label.toLowerCase()}</button></div><div className="map-board"><div className="map-board-head"><div><span className="demo-label">Dependency view</span><h3>{fact.label} <span>→</span> {affected.length} assets</h3></div><span className="count-pill">{affected.length} connected</span></div><div className="map-lines">{affected.map((asset, index) => <div className="map-node-row" key={asset.id}><div className="line"><i /></div><div className="map-node"><span className="asset-thumb">{asset.type[0]}</span><span><b>{asset.type}</b><small>{asset.channel} · owned by {asset.owner}</small></span><Status status={asset.status} /></div></div>)}</div><div className="map-note"><span>i</span> A change creates a review item and invalidates the approval for this asset version.</div></div></div></section>; }
function Reports({ report, setReport }: { report: { rows: number; checks: { line: number; severity: string; code: string; message: string }[]; valid: boolean } | null; setReport: (report: { rows: number; checks: { line: number; severity: string; code: string; message: string }[]; valid: boolean } | null) => void }) { const [csv, setCsv] = useState('postId,date,reach,likes\npost-001,2026-09-01,1200,48\npost-002,2026-09-02,980,35'); async function run() { try { setReport(await api('/api/reports/import', { method: 'POST', body: JSON.stringify({ csv }) })); } catch { setReport({ rows: 0, checks: [{ line: 0, severity: 'error', code: 'request', message: 'Could not check this report.' }], valid: false }); } } return <section className="page"><PageTitle eyebrow="Explainable reports" title="Check the numbers before sharing" sub="Import a small CSV, inspect the warnings and export a handoff that a client can understand." /><div className="report-layout"><div className="panel import-panel"><div className="panel-head"><div><p className="eyebrow">1 · Import</p><h3>Paste a sample CSV</h3></div><span className="file-badge">CSV</span></div><textarea value={csv} onChange={(event) => setCsv(event.target.value)} rows={9} /><button className="primary wide" onClick={run}>Run data checks <span>→</span></button><p className="helper">Data stays in this browser session. No platform account or API key is connected.</p></div><div className="panel report-result"><div className="panel-head"><div><p className="eyebrow">2 · Review</p><h3>{report ? (report.valid ? 'Ready to explain' : 'Needs attention') : 'No report checked yet'}</h3></div>{report && <span className={report.valid ? 'result-icon good' : 'result-icon bad'}>{report.valid ? '✓' : '!'}</span>}</div>{report ? <><div className="report-score"><strong>{report.rows}</strong><span>rows inspected</span><strong>{report.checks.length}</strong><span>flags</span></div>{report.checks.length ? report.checks.map((check, index) => <div className="check-row" key={`${check.code}-${index}`}><span className="warning">!</span><span><b>Line {check.line} · {check.code.replaceAll('_', ' ')}</b><small>{check.message}</small></span></div>) : <div className="empty"><span>✓</span><p>Clean sample. Every row has a usable ID and date.</p></div>}<button className="ghost wide" onClick={() => { const data = JSON.stringify(report, null, 2); const href = URL.createObjectURL(new Blob([data], { type: 'application/json' })); const link = document.createElement('a'); link.href = href; link.download = 'studiodesk-report-check.json'; link.click(); URL.revokeObjectURL(href); }}>Download data-quality summary</button></> : <div className="empty"><span>▤</span><p>Your quality summary will appear here.</p></div>}</div></div></section>; }
function Portal({ snapshot, pending, onApprove }: { snapshot: Snapshot; pending: number; onApprove: () => void }) { const ready = snapshot.campaign.assets.filter((asset) => asset.status === 'approved').length; return <section className="page portal-page"><div className="portal-banner"><span className="demo-label">Client preview · synthetic campaign</span><h2>Review the launch with confidence.</h2><p>Everything your team needs to see before content goes live, without sharing internal workspace details.</p><div className="portal-summary"><span><b>{ready}/{snapshot.campaign.assets.length}</b> approved assets</span><span><b>{pending}</b> need review</span><span><b>{Object.keys(snapshot.campaign.facts).length}</b> campaign facts</span></div></div><div className="panel client-checklist"><div className="panel-head"><div><p className="eyebrow">Client checklist</p><h3>Review outstanding items</h3></div><button className="ghost">Download handoff ↗</button></div>{snapshot.campaign.assets.map((asset) => <div className="client-row" key={asset.id}><span className={asset.status === 'approved' ? 'check-circle done' : 'check-circle'}>{asset.status === 'approved' ? '✓' : '!'}</span><span><b>{asset.type}</b><small>{asset.channel} · version {asset.version}</small></span><Status status={asset.status} /></div>)}</div><div className="portal-tip"><span>✦</span><p><b>Approvals are version-specific.</b> If a venue or price changes, StudioDesk will ask you to review only the affected materials.</p></div></section>; }
function PageTitle({ eyebrow, title, sub }: { eyebrow: string; title: string; sub: string }) { return <div className="page-title"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{sub}</p></div>; }
function Status({ status }: { status: string }) { const labels: Record<string, string> = { approved: 'Approved', outdated: 'Needs update', needs_review: 'Needs review' }; return <span className={`status ${status}`}><i />{labels[status] || status}</span>; }

export default App;
